---
title: Introduction to Voltammetry
---

This website is a sand-box for an initial imagining of *Analytical Chemistry 3.0* in which the pedagogical capabilities of digital tools are used to explore the possibilities for a **native-digital textbook**---a textbook fully conceived within a digital envrionment---instead of a **proto-digital textbook** that simply is a reformatting of a print textbook. Although voltammetry serves as a topic for this exploration, the materials here are not intended to be complete, nor are they intended to be suitable for a particular level of instruction.

Each student begins the semester with an identical set of materials. Because the files are hosted on a student's individual computer and are viewed through a local browser only, each student maintains a pesonalized version of *Analytical Chemistry 3.0*.

### About

A brief explanation of how this website was developed.

### Short Reads

Short reads are intended to provide students with a short, focused introduction to selected topics. A typical class session might focus on one or more short reads, which students read through in preparation for class, or elaborate on an important point raised during class. Some short reads might include questions for students to consider, perhaps in preparation for a class session, or a follow up question to extend their understanding of a topic. Collectively these short reads might serve as a student's primary textual resource.

Students can edit these `.RMd` files by adding annotations and entering their answers to questions using `Rmarkdown` and `R` code. 

### Problems

A collection of individual problems set for students to work. A typical problem set might consist of one or more problems that review or build on topics covered during a particular class session.

Students can edit these `.Rmd` files with their answers using `Rmarkdown`, embedding chunks of `R` code for quantitative work.

### Notes

A collection of notes, some provided by the instructor and others added by the students. Notes from the instructor might consist of a list of key terms, key equations, or copies of class notes. Notes generated by students might include information gathered from external resouces with a hyperlink back to the original source.

Students can use `Rmarkdown` to edit those `.Rmd` files generated by the instructor and generate new `.Rmd` files for their own use.

### `R` Functions

A collection of reference materials that explain and demonstrate the use of the available `R` functions. Students can consult these documents to review the available functions and how to use them. 

The `R` functions developed for these materials are intended to provide students with simple commands that allow them to explore data without the need for coding experience. For example, a student can use the function `cvSim` to simulate the result of a cyclic voltammetry experiment and use the function `plotCV` to view the result of that simulation without needing to understand the theoretical basis of the simulation or the code used to complete the simulation and plot the results. For advanced students, or a student interested in "peeking under the hood," the code itself is available here with, where appropriate, comments. 

### References

A collection of external references that students might find useful. Where possible, links to the sources are included.